# Site settings
title: "Překlady a historické texty"
author: "Alena Vondrušová"
description: "Překlady z a do němčiny, jazykové korektury, přepisy a překlady historických textů z kurentu a švabachu."
keywords: "Překlady, překlad, německý jazyk, český jazyk, korektura, přepis, přepisy, švabach, kurent"
#biography: "I am a Professor of Software Engineering at the <a href='http://www.fe.up.pt'>Faculty of Engineering</a>, University of Porto and Senior Researcher at <a href='https://www.inesctec.pt'>INESC TEC</a>. Here you can find my <a href='/assets/thesis.pdf'>PhD Thesis</a> and my <a href='/assets/cv.pdf'>Résumé</a>."
#colophon: "© MMXIII — MMXVI by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://hugosereno.eu"

ico: 12345678
bankAccount: AAA-XXXXXXXXX/YYYY
email: alena.vondrusova@gmail.com
phone: +420 728 232 468
#twitter_username: ferreira_hugo
#github_username: hugoferreira
#linkedin_username: hugoserenoferreira
#facebook_username: hugo.sereno.ferreira
google-analytics: UA-69060-5-xxxx

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
